import type { SupabaseClient } from "@supabase/supabase-js";
import { createAdminClient } from "@/lib/supabase/admin";
import { getPartnerRequestById } from "@/features/partnerRequests/queries";
import type { PartnerRequestDeliveryPurpose, PartnerRequestStatus } from "@/features/partnerRequests/types";
import { canReceivePartnerRequests } from "@/features/partners/canReceivePartnerRequests";
import type { HotelPartnerConsentStatus } from "@/types/database";
import { getWhatsAppProvider } from "./provider";
import type { WhatsAppPreSendError, WhatsAppProvider, WhatsAppSendResult } from "./types";

/**
 * Split into TWO steps — prepareWhatsAppPartnerRequest (eligibility +
 * payload content, no network) and sendPreparedPartnerRequestTemplate (the
 * actual provider call, given reply-token BUTTONS already generated by the
 * caller) — because features/partnerRequests/deliveryService.ts must wrap
 * the DELIVERY LIFECYCLE (queued -> sending -> sent/failed/unknown,
 * 0023_partner_request_deliveries.sql) tightly around the actual network
 * call: the reply-token hashes must be durably persisted BEFORE the
 * provider is ever called (task section 11, steps A-C), which this file
 * alone has no reason to know about — it never touches
 * partner_request_deliveries itself.
 *
 * IDEMPOTENCE — WHAT IS AND ISN'T GUARANTEED (unchanged reasoning from the
 * design audit that preceded 0023): apply_partner_request_command()'s own
 * row lock + status guard (0020_partner_requests.sql) already prevents an
 * inconsistent partner_requests.status or more than one `sent_to_partner`
 * event. What THIS file cannot guarantee on its own is whether Meta itself
 * received the SAME logical attempt twice — that is exactly why
 * deliveryService.ts now records `unknown` (never a silent retry) whenever
 * sendTemplateMessage() cannot distinguish "Meta rejected it" from "no
 * response ever arrived" — see metaProvider.ts's own doc comment on that
 * distinction.
 */

const E164_PATTERN = /^\+[1-9][0-9]{7,14}$/; // duplicated deliberately — see canReceivePartnerRequests.ts's own doc comment on this precedent
const PARTNER_REQUEST_TEMPLATE_ENV = "WHATSAPP_PARTNER_REQUEST_TEMPLATE";
const TEMPLATE_LANGUAGE_CODE = "fr";

/**
 * Maps the partner_request's CURRENT status to the delivery `purpose` this
 * attempt represents — never a caller-supplied value, to make a
 * purpose/status mismatch structurally impossible. pending_confirmation is
 * only ever reached once, right after guest_confirm — any send from that
 * status IS the initial request. alternative_proposed is only reachable
 * after guest_accept_alternative (0020's own rule: that command never
 * moves status directly to sent_to_partner) — any send from that status IS
 * the retransmission of the guest's acceptance.
 */
function purposeForStatus(status: PartnerRequestStatus): PartnerRequestDeliveryPurpose | null {
  if (status === "pending_confirmation") return "initial_request";
  if (status === "alternative_proposed") return "alternative_acceptance";
  return null;
}

/**
 * Deliberately NOT exported from features/partners/queries.ts (that file's
 * functions require an authenticated hotel_admin/superadmin session — see
 * its own doc comment) — this is a SYSTEM/service_role read, same posture
 * as features/partnerRequests/chatbotService.ts. Selects EXACTLY the
 * operational fields canReceivePartnerRequests() needs, nothing browser-
 * facing (never merged into features/partners/queries.ts's own
 * PARTNER_COLUMNS).
 */
interface PrivatePartnerForNotification {
  id: string;
  hotel_id: string;
  name: string;
  category: string;
  is_active: boolean;
  consent_status: HotelPartnerConsentStatus;
  whatsapp_consent_status: HotelPartnerConsentStatus;
  request_phone_e164: string | null;
}

async function getPartnerForNotification(hotelId: string, partnerId: string, supabase: SupabaseClient): Promise<PrivatePartnerForNotification | null> {
  const { data, error } = await supabase
    .from("hotel_partners")
    .select("id, hotel_id, name, category, is_active, consent_status, whatsapp_consent_status, request_phone_e164")
    .eq("id", partnerId)
    .eq("hotel_id", hotelId)
    .maybeSingle<PrivatePartnerForNotification>();
  if (error) throw new Error(error.message);
  return data;
}

async function getHotelName(hotelId: string, supabase: SupabaseClient): Promise<string | null> {
  const { data, error } = await supabase.from("hotels").select("name").eq("id", hotelId).maybeSingle<{ name: string }>();
  if (error) throw new Error(error.message);
  return data?.name ?? null;
}

/** A short, non-sensitive, non-reversible-to-anything-useful reference for human correspondence ("votre demande n° ..."). Never the full UUID — see this module's own "never send internal UUIDs" rule. */
function shortReference(partnerRequestId: string): string {
  return partnerRequestId.replace(/-/g, "").slice(0, 8).toUpperCase();
}

/** First word only — "éventuellement prénom du client si nécessaire" (task section 7), never the guest's full name. */
function firstNameOnly(guestName: string | null): string | null {
  const trimmed = guestName?.trim();
  if (!trimmed) return null;
  return trimmed.split(/\s+/)[0];
}

export interface PreparedPartnerRequestTemplate {
  purpose: PartnerRequestDeliveryPurpose;
  requestPhoneE164: string;
  templateName: string;
  languageCode: string;
  bodyParams: string[];
}

export type PrepareWhatsAppPartnerRequestResult = { ok: true; prepared: PreparedPartnerRequestTemplate } | { ok: false; error: WhatsAppPreSendError };

export interface PrepareWhatsAppPartnerRequestDeps {
  supabase?: SupabaseClient;
}

/**
 * All eligibility checks + the template's business content — NO network
 * call, NO reply tokens, NO knowledge of partner_request_deliveries.
 * Purely "is this request/partner eligible right now, and if so what
 * should the message say".
 */
export async function prepareWhatsAppPartnerRequest(
  requestId: string,
  hotelId: string,
  deps: PrepareWhatsAppPartnerRequestDeps = {}
): Promise<PrepareWhatsAppPartnerRequestResult> {
  const supabase = deps.supabase ?? createAdminClient();

  const request = await getPartnerRequestById(hotelId, requestId, supabase);
  if (!request) return { ok: false, error: "request_not_found" };

  const purpose = purposeForStatus(request.status);
  if (!purpose) return { ok: false, error: "request_not_eligible" };

  const partner = await getPartnerForNotification(hotelId, request.partner_id, supabase);
  if (!partner) return { ok: false, error: "partner_not_eligible" };

  // Phone checked BEFORE the bundled canReceivePartnerRequests() gate on
  // purpose: that function's own contract already folds "is
  // request_phone_e164 present and E.164-shaped" into its single boolean,
  // which would otherwise make missing_phone/invalid_phone unreachable.
  // Checking phone shape here FIRST, then calling canReceivePartnerRequests
  // once the phone is already known valid, is what makes the distinct
  // missing_phone/invalid_phone/partner_not_eligible error codes this
  // function promises actually distinguishable — by the time
  // canReceivePartnerRequests runs below, ONLY is_active/consent status can
  // make it return false.
  if (!partner.request_phone_e164) return { ok: false, error: "missing_phone" };
  if (!E164_PATTERN.test(partner.request_phone_e164)) return { ok: false, error: "invalid_phone" };

  if (!canReceivePartnerRequests(partner)) return { ok: false, error: "partner_not_eligible" };

  const templateName = process.env[PARTNER_REQUEST_TEMPLATE_ENV];
  if (!templateName) return { ok: false, error: "template_not_configured" };

  const hotelName = await getHotelName(hotelId, supabase);
  if (!hotelName) return { ok: false, error: "request_not_eligible" };

  // Business content ONLY — see this module's own "never send" list.
  // Deliberately NEVER included: guest_phone_e164, hotel_id, conversation_id,
  // the partner_request's own full UUID, any access/verify token.
  const bodyParams = [
    hotelName,
    request.request_category,
    request.requested_date ?? "—",
    request.requested_time ?? "—",
    request.party_size ? String(request.party_size) : "—",
    request.details ?? "—",
    firstNameOnly(request.guest_name) ?? "—",
    shortReference(request.id),
  ];

  return {
    ok: true,
    prepared: {
      purpose,
      requestPhoneE164: partner.request_phone_e164,
      templateName,
      languageCode: TEMPLATE_LANGUAGE_CODE,
      bodyParams,
    },
  };
}

export interface PartnerReplyButtonTokens {
  accept: string;
  reject: string;
  alternative: string;
}

export interface SendPreparedPartnerRequestDeps {
  provider?: WhatsAppProvider;
}

/**
 * The ONLY place a WhatsApp template message actually leaves this server.
 * `replyTokens` are the RAW opaque tokens (never their hashes) — generated
 * by, and whose hashes are already durably persisted by, the caller
 * (deliveryService.ts::deliverPartnerRequest) BEFORE this function is ever
 * invoked (task section 11, steps A-C precede step D, this function).
 */
export async function sendPreparedPartnerRequestTemplate(
  prepared: PreparedPartnerRequestTemplate,
  replyTokens: PartnerReplyButtonTokens,
  deps: SendPreparedPartnerRequestDeps = {}
): Promise<WhatsAppSendResult> {
  const provider = deps.provider ?? getWhatsAppProvider();

  return provider.sendTemplateMessage({
    toE164: prepared.requestPhoneE164,
    templateName: prepared.templateName,
    languageCode: prepared.languageCode,
    bodyParams: prepared.bodyParams,
    buttons: [
      { label: "Accepter", payload: replyTokens.accept },
      { label: "Refuser", payload: replyTokens.reject },
      { label: "Proposer une alternative", payload: replyTokens.alternative },
    ],
  });
}
